# Matrix HomeWork NumPy  

In [1]:
import numpy as np


# Step 1: Define two 3x3 matrices A and B


In [10]:
A = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

B = np.array([[7, 8, 9],
              [1, 3, 5],
              [2, 4, 6]])



# Compute individual terms


In [11]:
A_squared = A @ A
AB = A @ B
AT_BT = A.T @ B.T


# Use pseudo-inverse since B is singular


In [12]:
B_inv = np.linalg.pinv(B)
term_Binv_BT = B_inv @ B.T


# Determinant of AB


In [13]:
det_AB = np.linalg.det(AB)


# A cubed and B cubed


In [14]:
A_cubed = A @ A @ A
B_cubed = B @ B @ B
term_A3B3 = A_cubed @ B_cubed


# 3(B - A)


In [15]:
term_3_BminusA = 3 * (B - A)


# Final result


In [18]:
C = A_squared + AB - AT_BT + term_Binv_BT + term_A3B3 + term_3_BminusA + det_AB

np.set_printoptions(precision=4, suppress=True)
print("Matrix C =\n", C)


Matrix C =
 [[157760.419  264486.8544 371163.6993]
 [129121.1493 217117.9569 305032.9832]
 [297475.8796 496542.0594 695597.2671]]
